import { PATTERN_LABELS } from "../domain/pattern.js";
import { QUADRANT_LABELS, type AuditResult, type Opportunity } from "../prioritize/audit.js";
import { ROI_INPUT_LABELS } from "../roi/model.js";
import { escapeMarkdownCell as cell, money, months, num, pct, rangeText } from "./format.js";
import { roadmap, summarize } from "./summary.js";

export interface ReportMeta {
  title: string;
  generator: string;
  sources: string[];
  /** Relative path of the quadrant image from the markdown file. */
  quadrantImage: string;
}

function table(headers: string[], rows: string[][]): string {
  const line = (cells: string[]) => `| ${cells.join(" | ")} |`;
  return [line(headers), line(headers.map(() => "---")), ...rows.map(line)].join("\n");
}

function roadmapRow(o: Opportunity, currency: string): string[] {
  const e = o.economics;
  if (!e) return [];
  const net = e.simulation.firstYearNet;
  return [
    String(o.rank),
    cell(o.workflowName),
    cell(o.stepName),
    PATTERN_LABELS[o.pattern],
    num(e.value),
    num(e.effort.score),
    num(e.simulation.hoursSavedPerMonth.p50),
    `${money(net.p10, currency)} / ${money(net.p50, currency)} / ${money(net.p90, currency)}`,
    months(e.simulation.paybackMonths.p50),
    pct(e.simulation.probabilityPositiveFirstYear),
  ];
}

function opportunityDetail(o: Opportunity, currency: string): string {
  const e = o.economics;
  if (!e) return "";
  const sim = e.simulation;
  const lines: string[] = [
    `### ${o.rank}. ${o.workflowName}: ${o.stepName}`,
    "",
    `**${PATTERN_LABELS[o.pattern]}** · ${QUADRANT_LABELS[e.quadrant]} (value ${num(e.value)}, effort ${num(e.effort.score)}) · actor: ${o.actor}`,
    "",
    o.patternRationale,
    "",
    `Friction **${num(o.friction.score)}** · AI suitability **${num(o.suitability.score)}**`,
    "",
    table(
      ["Score", "Factor", "Value", "Weight", "Points", "Why"],
      [
        ...o.friction.factors.map((f) => [
          "Friction",
          f.factor,
          num(f.value, 2),
          num(f.weight, 2),
          num(f.points, 1),
          cell(f.note),
        ]),
        ...o.suitability.factors.map((f) => [
          "Suitability",
          f.factor,
          num(f.value, 2),
          num(f.weight, 2),
          num(f.points, 1),
          cell(f.note),
        ]),
      ],
    ),
    "",
    `Effort ${num(e.effort.score)} = ${e.effort.components.map((c) => `${num(c.points)} (${c.note})`).join(" + ")}`,
    "",
    table(
      ["Metric", "Likely-input estimate", "P10", "P50", "P90"],
      [
        [
          "Hours saved / month",
          num(e.point.hoursSavedPerMonth),
          num(sim.hoursSavedPerMonth.p10),
          num(sim.hoursSavedPerMonth.p50),
          num(sim.hoursSavedPerMonth.p90),
        ],
        [
          "Net savings / month",
          money(e.point.monthlyNet, currency),
          money(sim.monthlyNet.p10, currency),
          money(sim.monthlyNet.p50, currency),
          money(sim.monthlyNet.p90, currency),
        ],
        [
          "First-year net",
          money(e.point.firstYearNet, currency),
          money(sim.firstYearNet.p10, currency),
          money(sim.firstYearNet.p50, currency),
          money(sim.firstYearNet.p90, currency),
        ],
        [
          "Payback",
          months(e.point.paybackMonths),
          months(sim.paybackMonths.p10),
          months(sim.paybackMonths.p50),
          months(sim.paybackMonths.p90),
        ],
      ],
    ),
    "",
    "Sensitivity of first-year net (one input at a time, others at likely):",
    "",
    table(
      ["Input", "Range", "Net at low", "Net at high", "Swing"],
      e.tornado
        .slice(0, 5)
        .map((b) => [
          ROI_INPUT_LABELS[b.input],
          `${num(b.lowInput, b.lowInput < 1 ? 2 : 0)} – ${num(b.highInput, b.highInput < 1 ? 2 : 0)}`,
          money(b.outputAtLow, currency),
          money(b.outputAtHigh, currency),
          money(b.swing, currency),
        ]),
    ),
  ];
  if (o.guardrails.length > 0) {
    lines.push("", "Guardrails:", "", ...o.guardrails.map((g) => `- ${g}`));
  }
  return lines.join("\n");
}

export function renderMarkdown(result: AuditResult, meta: ReportMeta): string {
  const s = summarize(result);
  const c = s.currency;
  const cfg = result.config;
  const parts: string[] = [`# ${meta.title}`, ""];

  if (s.syntheticWorkflows > 0) {
    parts.push(
      `> **Synthetic data.** ${s.syntheticWorkflows} of ${s.workflows} workflows are marked synthetic. Figures illustrate the method and are not measurements of any real organization.`,
      "",
    );
  }
  parts.push(
    `Generated by ${meta.generator} from ${meta.sources.map((src) => `\`${src}\``).join(", ")}. Monte Carlo: ${num(cfg.simulation.iterations)} iterations, seed ${cfg.simulation.seed}.`,
    "",
    "## Summary",
    "",
    `- ${s.stepsAssessed} human steps assessed across ${s.workflows} workflows; ${s.recommended} recommended (${PATTERN_LABELS.copilot}: ${s.byPattern.copilot}, ${PATTERN_LABELS.automation_with_review}: ${s.byPattern.automation_with_review}, ${PATTERN_LABELS.agent}: ${s.byPattern.agent}), ${s.byPattern.not_recommended} not recommended.`,
    `- Now + Next (${s.nowNextCount} opportunities): ${num(s.nowNextHoursP50)} hours saved per month and ${money(s.nowNextFirstYearNetP50, c)} first-year net, as sums of per-opportunity medians (not a portfolio percentile).`,
    "",
    "## Roadmap",
    "",
  );

  const headers = [
    "#",
    "Workflow",
    "Step",
    "Pattern",
    "Value",
    "Effort",
    "Hours/mo P50",
    `First-year net P10 / P50 / P90`,
    "Payback P50",
    "P(net > 0)",
  ];
  for (const phase of roadmap(result)) {
    parts.push(`### ${phase.title}`, "", phase.description, "");
    parts.push(
      phase.opportunities.length > 0
        ? table(
            headers,
            phase.opportunities.map((o) => roadmapRow(o, c)),
          )
        : "_None._",
      "",
    );
  }
  if (s.notRecommended.length > 0) {
    parts.push(
      "### Not recommended",
      "",
      table(
        ["Workflow", "Step", "Friction", "Suitability", "Reason"],
        s.notRecommended.map((o) => [
          cell(o.workflowName),
          cell(o.stepName),
          num(o.friction.score),
          num(o.suitability.score),
          cell(o.patternRationale),
        ]),
      ),
      "",
    );
  }

  parts.push(
    "## Value vs effort",
    "",
    `![Value vs effort quadrant](${meta.quadrantImage})`,
    "",
    "## Workflows",
    "",
  );
  parts.push(
    table(
      [
        "Workflow",
        "Team",
        "Volume / month",
        "Labor hours / month",
        "Friction",
        "Human / system steps",
        "Synthetic",
      ],
      result.workflows.map((w) => [
        cell(w.name),
        cell(w.team),
        rangeText(w.volumePerMonth),
        num(w.laborHoursPerMonth),
        num(w.friction),
        `${w.humanSteps} / ${w.systemSteps}`,
        w.synthetic ? "yes" : "no",
      ]),
    ),
    "",
    "## Opportunity details",
    "",
  );
  for (const o of result.opportunities) {
    if (o.economics) parts.push(opportunityDetail(o, c), "");
  }

  parts.push(
    "## Method",
    "",
    "- **Friction** (0-100): weighted average of hands-on time, rework rate, handoffs, and wait time, each normalized against a saturation point.",
    "- **AI suitability** (0-100): weighted average of task-type fit, data readiness, judgment required (inverted), and regulatory risk (inverted).",
    "- **Hours saved / month** = volume × share of runs reaching the step × minutes × (1 + rework rate) ÷ 60 × automation fraction for the pattern.",
    "- **First-year net** = 12 × (hours saved × loaded hourly cost − monthly run cost) − implementation cost. Every input is a triangular distribution sampled independently.",
    `- **Value** = P50 annual net savings ÷ ${money(cfg.prioritization.valueCapAnnual, c)} (capped at 100). **Effort** = pattern base + data readiness, regulatory, and integration penalties. Quadrant thresholds: value ${cfg.prioritization.valueThreshold}, effort ${cfg.prioritization.effortThreshold}.`,
    "- All weights, thresholds, cost bands, and automation fractions are in the configuration file passed with `--config` (defaults in `config/default.yaml`).",
    "",
  );
  return parts.join("\n");
}
